#!/bin/sh
# husky

# Created by Husky v4.3.8 (https://github.com/typicode/husky#readme)
#   At: 11/17/2022, 9:58:53 AM
#   From: /Users/hualun/pros/test/low_code/form-create-designer/node_modules/husky (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
